apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: backend
    spec:
      containers:
       - image: mongo
         name: mongodb
         volumeMounts:
          - name: mongodb-data
            mountPath: /data/db
         ports:
          - containerPort: 27017
            protocol: TCP
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc