apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  containers:
    - image: mongo
      name: mongo
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      ports:
        - containerPort: 27017
          protocol: TCP
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: mongo-pvc